#!/usr/bin/env python3
"""Generate the C++ built-in mod ID manifest used by runtime validation."""

import argparse
import json
from pathlib import Path
import sys


def strip_jsonc_comments(text: str) -> str:
    """Remove // and /* */ comments while preserving quoted strings."""
    result: list[str] = []
    index = 0
    in_string = False
    escaped = False

    while index < len(text):
        char = text[index]
        next_char = text[index + 1] if index + 1 < len(text) else ""
        if in_string:
            result.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
        elif char == '"':
            in_string = True
            result.append(char)
            index += 1
        elif char == "/" and next_char == "/":
            index += 2
            while index < len(text) and text[index] not in "\r\n":
                index += 1
        elif char == "/" and next_char == "*":
            index += 2
            while index + 1 < len(text) and not ( text[index] == "*" and text[index + 1] == "/" ):
                if text[index] in "\r\n":
                    result.append(text[index])
                index += 1
            index += 2
        else:
            result.append(char)
            index += 1
    return "".join(result)


def strip_trailing_commas(text: str) -> str:
    """Remove commas before a closing JSON array or object."""
    result: list[str] = []
    index = 0
    in_string = False
    escaped = False

    while index < len(text):
        char = text[index]
        if in_string:
            result.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
            continue
        if char == '"':
            in_string = True
            result.append(char)
            index += 1
            continue
        if char == ",":
            lookahead = index + 1
            while lookahead < len(text) and text[lookahead].isspace():
                lookahead += 1
            if lookahead < len(text) and text[lookahead] in "]}":
                index += 1
                continue
        result.append(char)
        index += 1
    return "".join(result)


def find_mod_ids(value: object, path: Path) -> set[str]:
    result: set[str] = set()
    if isinstance(value, dict):
        if value.get("type") == "MOD_INFO":
            mod_id = value.get("id")
            if not isinstance(mod_id, str) or not mod_id:
                raise ValueError(f"{path}: MOD_INFO has no string id")
            result.add(mod_id)
        for child in value.values():
            result.update(find_mod_ids(child, path))
    elif isinstance(value, list):
        for child in value:
            result.update(find_mod_ids(child, path))
    return result


def cxx_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_header(output: Path, available: bool, mod_ids: list[str]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    entries = ",\n".join(f"    {cxx_string(mod_id)}" for mod_id in mod_ids)
    output.write_text(
        "// This file is generated by tools/generate_builtin_mods.py.\n"
        "#pragma once\n"
        "#ifndef CATA_SRC_BUILTIN_MODS_H\n"
        "#define CATA_SRC_BUILTIN_MODS_H\n\n"
        "#include <array>\n"
        "#include <string_view>\n\n"
        f"constexpr bool builtin_mod_manifest_available = {'true' if available else 'false'};\n"
        f"constexpr std::array<std::string_view, {len(mod_ids)}> builtin_mod_ids = {{\n"
        f"{entries}\n"
        "};\n\n"
        "#endif // CATA_SRC_BUILTIN_MODS_H\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if not args.source.is_dir():
        print(f"Built-in mod directory does not exist: {args.source}", file=sys.stderr)
        write_header(args.output, False, [])
        return 0

    try:
        mod_ids: set[str] = set()
        for modinfo in args.source.rglob("modinfo.json"):
            text = modinfo.read_text(encoding="utf-8")
            value = json.loads(strip_trailing_commas(strip_jsonc_comments(text)))
            mod_ids.update(find_mod_ids(value, modinfo))
        write_header(args.output, True, sorted(mod_ids))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Unable to generate built-in mod manifest: {error}", file=sys.stderr)
        write_header(args.output, False, [])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
