name: Detect missions that are missing .start.assign_mission_target.om_special

on:
  pull_request:
    paths:
      - '**.json'

permissions:
  contents: read

jobs:
  run-the-tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - run: ./tools/json_tools/assign_mission_target_needs_om_special.bash 2>&1
